In [3]:
"""Backpropogration is the process of going back after the first run in the neural networks 
to update the weights and biases"""

# We want to change the weights so that loss function is minimized - Gradient Descent

'Backpropogration is the process of going back after the first run in the neural networks \nto update the weights and biases'

In [4]:
"""L-3 L-2 L-1 L

Between each L, those happen below:
    1) X is input which is given to function Z
    2) z = wx + b Function z convert X by adding up W weight and B bias 
    3) activation function applied: sigma(z) - output of Z is given to activation function
    4) output is activation function is given to next neuron - layer
    """

'L-3 L-2 L-1 L\n\nBetween each L, those happen below:\n    1) X is input which is given to function Z\n    2) z = wx + b Function z convert X by adding up W weight and B bias \n    3) activation function applied: sigma(z) - output of Z is given to activation function\n    4) output is activation function is given to next neuron - layer\n    '

In [5]:
import torch

In [6]:
x = torch.tensor(2.0, requires_grad=True)

In [7]:
x

tensor(2., requires_grad=True)

In [8]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1

In [10]:
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [11]:
y.backward()

In [12]:
x.grad

tensor(93.)

In [14]:
x = torch.tensor([[1., 2., 3.],[3., 2., 1.]], requires_grad=True)

In [15]:
x

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)

In [16]:
y = 3*x + 2

In [17]:
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [18]:
z = 2*y**2

In [19]:
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [20]:
out = z.mean()

In [21]:
out

tensor(140., grad_fn=<MeanBackward0>)

In [22]:
out.backward()

In [23]:
x.grad

tensor([[10., 16., 22.],
        [22., 16., 10.]])