In [2]:
import torch
import numpy as np

In [5]:
torch.__version__

'1.5.0'

In [7]:
arr = np.array([1,2,3,4,5])

In [8]:
arr

array([1, 2, 3, 4, 5])

In [10]:
arr.dtype

dtype('int32')

In [13]:
# Numpy Array - > Pytorch Tensor
x = torch.from_numpy(arr)

In [14]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [15]:
type(x)

torch.Tensor

In [17]:
xx = torch.as_tensor(arr)

In [18]:
type(xx)

torch.Tensor

In [19]:
xx

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [20]:
arr_2d = np.arange(0.0, 12.0)

In [23]:
arr_2d = arr_2d.reshape(4,3)

In [24]:
x_2d = torch.from_numpy(arr_2d)

In [25]:
x_2d

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [30]:
# Array is linked even if converted
arr[0] = 99

In [29]:
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [31]:
# Remove the direct link
arr

array([99,  2,  3,  4,  5])

In [32]:
arr_w = np.arange(0,10)

In [33]:
arr_w

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
my_tens = torch.tensor(arr_w)
my_tens_2 = torch.as_tensor(arr_w)
my_tens_2 = torch.from_numpy(arr_w)

In [35]:
my_tens

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [3]:
e_arr = np.array([1,2,3])

In [6]:
type(e_arr)

numpy.ndarray

In [9]:
# float tensor if Tensor is capital
torch.Tensor(e_arr)
torch.FloatTensor(e_arr)

tensor([1., 2., 3.])

In [8]:
torch.tensor(e_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [13]:
# Creating a tensor placeholder
torch.empty(3,2)

tensor([[1.0779e-08, 2.0447e+23],
        [1.0617e+21, 2.6704e-06],
        [4.0975e-11, 7.1450e+31]])

In [22]:
torch.zeros(5,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
torch.arange(0,10, 3)

tensor([0, 3, 6, 9])

In [30]:
torch.linspace(0,12,12).reshape(2,6)

tensor([[ 0.0000,  1.0909,  2.1818,  3.2727,  4.3636,  5.4545],
        [ 6.5455,  7.6364,  8.7273,  9.8182, 10.9091, 12.0000]])

In [31]:
my_tensor = torch.tensor([1,2,3])

In [32]:
my_tensor.dtype

torch.int64

In [37]:
# convret to 32 int
my_tensor = my_tensor.type(torch.int32)

In [38]:
my_tensor.dtype

torch.int32

In [41]:
torch.rand(4,10)

tensor([[0.9722, 0.6599, 0.9975, 0.2369, 0.5817, 0.9498, 0.3241, 0.4988, 0.3108,
         0.9516],
        [0.2415, 0.2909, 0.1058, 0.2475, 0.6570, 0.1509, 0.9302, 0.6072, 0.7961,
         0.9461],
        [0.0810, 0.8947, 0.9513, 0.7195, 0.8761, 0.3137, 0.9505, 0.9884, 0.5716,
         0.9424],
        [0.0538, 0.2803, 0.0885, 0.0028, 0.4120, 0.3662, 0.1369, 0.9938, 0.1785,
         0.6884]])

In [43]:
torch.randn(4,10)
# std = 1

tensor([[-0.8466, -1.3603,  0.0871, -0.1833, -1.1097,  0.0380,  1.5412,  0.7989,
         -0.1746,  0.8088],
        [ 0.6992,  0.6841,  0.3096,  0.1715,  1.1088,  0.6364, -0.5351, -1.0092,
          0.7441, -0.2952],
        [-0.5369, -0.1760,  0.5395,  0.1795,  0.3350, -0.6415,  0.0135,  1.2282,
         -2.1526, -0.8658],
        [ 0.5577, -1.5196,  2.1922, -0.3915, -0.9646, -0.9282, -0.9630, -0.1565,
         -1.8520,  0.4644]])

In [45]:
torch.randint(0,10, (5,5))

tensor([[9, 7, 3, 8, 9],
        [7, 0, 0, 5, 0],
        [5, 7, 2, 2, 2],
        [1, 8, 1, 6, 1],
        [8, 9, 2, 4, 5]])

In [46]:
torch.manual_seed(42)
torch.randint(0,10, (2,2))

tensor([[2, 7],
        [6, 4]])

In [48]:
# Tensor Operations
x = torch.arange(6).reshape(3,2)

In [49]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [50]:
# CPUs have more units related to Cache, Control, DRAM, etc. While GPUs have more Arithmetic Logic Units (ALU)
# which is the reason why GPUs are better in ML (Pytorch, as an example).
# ML uses matrix multiplication is backpropogation - while this process leads to a big matrix calculations
# Using GPUs enables parallel computing with the help of all those many ALUs

# NVIDIA created CUDA - parallel computing architechture - writing code for GPU parallel processing
# Pytorch GPU - NVIDIA
torch.cuda.is_available()

False